config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: [:new, :create, :update, :index, :show] do
    resources :reviews, only: [:create]
    resources :project_steps, only: [:create, :index]
    resources :user_projects, only: [:create, :show]
    resources :messages, only: :create
  end
  resources :user_projects, only: [:show, :update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <!-- NAVBAR CONTENT -->
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="d-flex align-items-center">
      <h1><%= link_to "ProgressHub", root_path, class: "nav-link" %></h1>
      <%= form_tag projects_path, class: "form", method: :get do %>
        <input class="search__input" name="query" type="text" placeholder="Search..">
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Create", new_project_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My projects", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <% else %>
              <%= image_tag "default-avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_tab_achieved.html.erb
<div class="tab-pane fade p-5" id="nav-achieved" role="tabpanel" aria-labelledby="nav-achieved-tab">
  <h1>Finished Projects</h1>
  <% finished_projects.each do |finished_project| %>
    <%= link_to user_project_path(finished_project) do %>
      <div class="card-proj-dashbord">
        <%= cl_image_tag finished_project.project.photo.key, alt: "alttext", width: 120, height: 120, crop: :thumb %>
        <div class="card-proj-infos w-100">
          <div class="proj-info-text">
            <h2><%= finished_project.project.title %></h2>
            <div class="d-flex justify-content-between">
              <div>
                <p>Completed!</p>
              </div>
            </div>
          </div>
          <div class="progress mt-2">
            <div class="progress-bar bg-info" role="progressbar" style="width: <%= 100 %>%" aria-valuenow="" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
    <% end  %>
  <% end  %>
</div>

app/views/shared/_tab_active.html.erb
<div class="tab-pane fade show active p-5" id="nav-act-proj" role="tabpanel" aria-labelledby="nav-act-proj-tab">
  <div class="tab-user-project-act-proj">
    <h1>On-going projects</h1>
    <% active_projects.each do |active_project| %>
      <%= link_to user_project_path(active_project) do %>
        <div class="card-proj-dashbord">
          <%= cl_image_tag active_project.project.photo.key, alt: "alttext", width: 120, height: 120, crop: :thumb %>
          <div class="card-proj-infos w-100">
            <div class="proj-info-text">
              <h2><%= active_project.project.title %></h2>
              <div class="d-flex justify-content-between">
                <div>
                  <p><strong><%= active_project.last_completed %> / <%= active_project.project.project_steps.count %> steps completed</strong></p>
                </div>
                <div>
                  <p>Next step: <%= active_project.next_step_header %></p>
                </div>
              </div>
            </div>
            <div class="progress mt-2">
              <div class="progress-bar bg-info" role="progressbar" style="width: <%= active_project.percent_completed %>%" aria-valuenow="" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
      <% end  %>
    <% end %>
  </div>
</div>

app/views/shared/_tab_create.html.erb
<div class="tab-pane fade p-5" id="nav-create" role="tabpanel" aria-labelledby="nav-create-tab">
  <% if projects_drafts.present?  %>
    <h1>Drafts</h1>
  <% end %>
  <% projects_drafts.each do |project_draft| %>
    <%= link_to user_project_path(project_draft) do %>
      <div class="card-proj-dashbord">
        <%= cl_image_tag project_draft.project.photo.key, alt: "alttext", width: 120, height: 120, crop: :thumb %>
        <div class="card-proj-infos w-100">
          <div class="proj-info-text">
            <h2><%= project_draft.project.title %></h2>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if projects_published.present? %>
    <h1>Projects you published</h1>
  <% end %>
  <% projects_published.each do |project_published| %>
    <%= link_to user_project_path(project_published) do %>
      <div class="card-proj-dashbord">
        <%= cl_image_tag project_published.project.photo.key, alt: "alttext", width: 120, height: 120, crop: :thumb %>
        <div class="card-proj-infos w-100">
          <div class="proj-info-text">
            <h2><%= project_published.project.title %></h2>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_tab_overview.html.erb
<div class="project-overview">
  <div class="container py-4">
    <div class="project-overview-hero d-flex justify-space-between mb-5">
      <div class="project-view-image mr-4">
        <%= cl_image_tag project.photo.key %>
      </div>
      <div class="project-overview-hero-info">
        <h1 class="mb-4"><%= project.title %></h1>

        <div class="created-by d-flex mb-4">
          <div class="avatar">
            <% if project.user.photo.attached? %>
              <%= cl_image_tag project.user.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "default-avatar.jpg", class: "avatar" %>
            <% end %>
          </div>
          <div class="pl-3">
            <p class="m-0">Created By</p>
            <p class="m-0"><%= project.user.username %></p>
          </div>
        </div>
        <%= image_tag "clock.png", alt: "clock-icon", id: "clock" %><%= project.esttime %>
      </div>
    </div>
    <div class="overview-info">
      <p><%= project.description %></p>

      <div class="project-step-preview ml-5">
        <% project.project_steps.order(:ordinal).each do |step| %>
          <div class="d-flex m-4">
            <%= cl_image_tag step.photo.key, :width=>150, :crop=>"scale" %>
            <div class="ml-2">
              <h2>Step <%= step.ordinal %></h2>
              <p><%= step.header %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tab_project_step.html.erb
<div class="project-step-image"><%= cl_image_tag (step.photo.key) if step.photo.attached? %></div>

<h2><%= step.header %></h2>
<p><%= step.description %></p>
<% if step.ordinal == @steps.count %>
  <%= simple_form_for @user_project, remote: true do |f| %>
    <%= f.input :completed, as: :hidden, input_html: {value: true} %>
    <%= f.submit "Finish Project", class: "btn landing-button btn-lg", "data-toggle": "modal", "data-target": "#exampleModalCenter" %>
  <% end %>
<% else %>
  <%= simple_form_for @user_project, remote: true, html: { 'data-next-tab': "tab-#{step.ordinal + 1}" } do |f| %>
    <%= f.input :last_completed, as: :hidden, input_html: {value: step.ordinal} %>
    <%= f.submit "Next step", class: "btn landing-button btn-lg"%>
  <% end %>
<% end %>

app/views/shared/_tab_project_step_show.html.erb
<div class="project-step-image"><%= cl_image_tag (step.photo.key) if step.photo.attached? %></div>

<h2><%= step.header %></h2>
<p><%= step.description %></p>