config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: [:new, :create, :update, :index, :show] do
    resources :reviews, only: [:create]
    resources :project_steps, only: [:create, :index]
    resources :user_projects, only: [:create, :show]
    resources :messages, only: :create
  end
  resources :user_projects, only: [:show, :update]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :project_steps, dependent: :destroy
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :messages, dependent: :destroy
  has_many :reviews
  validates :title, presence: true
  acts_as_taggable_on :tags


  after_create :create_user_project_for_creator

  private

  def create_user_project_for_creator
    UserProject.create(user: user, project: self)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :update]

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      @user_project = UserProject.find_by(user: current_user, project: @project)
      redirect_to user_project_path(@user_project)
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to "#{url_for(dashboard_path)}#nav-create", notice: "Published #{@project.title} project"
    else
      render "user_projects/show"
    end
  end

  def index
    if params[:query].present?
      relevant_projects = []
      relevant_projects << policy_scope(Project).tagged_with(params[:query])
      relevant_projects << policy_scope(Project).where('title ILIKE :query OR description ILIKE :query', query: "%#{params[:query]}%")
      # relevant_projects << policy_scope(Project).where('description ILIKE ?', "%#{params[:query]}%")
      @projects = Project.from("(#{relevant_projects.map(&:to_sql).join(' UNION ')}) AS projects")
    else
      @projects = policy_scope(Project)
    end
  end

  def show
    @steps = @project.project_steps.order(:ordinal)
    @user_project = UserProject.new()
    @reviews = Review.where(project: @project)
  end

  def tagged
  end

  private

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def project_params
    params.require(:project).permit(:title, :description, :photo, :published, tag_list: [])
  end
end

app/views/projects/index.html.erb
<div class="container py-4">
  <div class="cards">
    <% @projects.each do |project| %>
      <%= link_to project_path(project) do %>
        <div class="card-index" >
          <div class="image-with-overlay">
            <%= image_tag project.photo, alt: "card-img", class: "card-index-img" %>
            <div class="card-index-overlay"></div>
          </div>
          <div class="box p-3">
            <div class="card-index-info">
              <h2><%= project.title %></h2>
            </div>
            <div class="card-index-footer">
              <div class="card-index-footer-user align-items-center d-flex">
                <% if project.user.photo.attached? %>
                  <%= cl_image_tag project.user.photo.key, class: "avatar" %>
                <% else %>
                  <%= image_tag "default-avatar.jpg", class: "avatar" %>
                <% end %>
                <div class="ml-3">
                  <p class="m-0" >Created by</p>
                  <p class="m-0" ><%= project.user.username %></p>
                </div>
              </div>
              <div class="card-tags">
                <% project.tag_list.each do |keyword| %>
                  <span><%= keyword %></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
   <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container py-4">
  <div class="project-form">
    <div class="row justify-content-center">
      <div class="col-5">
        <h1>Create your project</h1>
        <%= simple_form_for (@project) do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Next", class: "btn landing-button btn-lg"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-2">
    <div class="nav nav-tabs flex-column tab-buttons-progresshub m-2" id="nav-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active mb-1" id="nav-overview-tab" data-toggle="tab" href="#nav-overview" role="tab" aria-controls="nav-overview" aria-selected="true">Overview</a>
      <% @steps.each do |step| %>
        <a class="nav-link mb-1" id="tab-<%= step.ordinal %>" data-toggle="tab" href="#nav-<%= step.ordinal %>" role="tab" aria-controls="nav-<%= step.ordinal %>" aria-selected="false"><%= "Step #{step.ordinal}" %></a>
      <% end %>
      <%# if current_user == @project.user %>
        <!-- <a class="nav-link mb-1" id="add-step-tab" data-toggle="tab" href="#nav-new-step" role="tab" aria-controls="nav-overview">Add step</a> -->
      <%# end %>
    </div>
  </div>
  <div class="col-6">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-overview" role="tabpanel" aria-labelledby="nav-overview-tab">
        <div class="tab-user-project-overview our-background">
          <%= render 'shared/tab_overview', project: @project  %>
        </div>
      <div class="reviews">
        <%= render 'reviews/index', reviews: @project.reviews %>
      </div>
      </div>
      <% @steps.each do |step| %>
        <div class="tab-pane fade p-5 our-background" id="nav-<%= step.ordinal %>" role="tabpanel" aria-labelledby="nav-<%= step.ordinal %>-tab">
          <%= render 'shared/tab_project_step_show', step: step %>
        </div>
      <% end %>
      <div class="tab-pane fade show our-background" id="nav-new-step" role="tabpanel" aria-labelledby="nav-overview-tab">
        <div class="tab-user-project-overview">
          <h1>New form</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="col-4">
      <%= render 'chatrooms/show', project: @project, user_project: @user_project %>
  </div>
</div>